#!/usr/bin/env python3
"""
make_mobile.py
==============
Builds a single self-contained wk_audio_quiz_mobile.html with:
  - All WaniKani subject data embedded inline
  - Audio files for selected levels embedded as base64 data URIs
    (so human voices work on Android Chrome with no server needed)

Run from your Japanese_Study folder:
    python make_mobile.py

You'll be asked which levels to embed audio for.
Levels you don't include fall back to browser TTS.
"""

import os
import sys
import json
import base64
import re

AUDIO_DIR   = "audio"
DATA_FILE   = "wk_data.js"
HTML_FILE   = "wk_audio_quiz.html"
OUTPUT_FILE = "wk_audio_quiz_mobile.html"
PLACEHOLDER = '<script src="wk_data.js"></script>'

# ── Check files ─────────────────────────────────────────────────────
for f in [DATA_FILE, HTML_FILE]:
    if not os.path.exists(f):
        sys.exit(f"\n✗ {f} not found. Make sure you're in the Japanese_Study folder.\n")

if not os.path.isdir(AUDIO_DIR):
    print(f"⚠  No '{AUDIO_DIR}' folder found — audio will fall back to TTS for all items.")
    audio_levels = set()
else:
    # Ask which levels to embed audio for
    print()
    print("╔══════════════════════════════════════╗")
    print("║  WaniKani Quiz — Mobile Builder      ║")
    print("╚══════════════════════════════════════╝")
    print()
    print("Audio files can be embedded for a level range.")
    print("More levels = larger file. Levels 1-10 ≈ 10-20 MB (fine for a phone).")
    print("Levels outside your range will use voice synthesis instead.")
    print()
    raw = input("Embed audio for levels (e.g. 1-10, or press Enter for 1-5): ").strip()
    if not raw:
        lmin, lmax = 1, 5
    else:
        parts = raw.replace(" ", "").split("-")
        try:
            lmin = int(parts[0])
            lmax = int(parts[1]) if len(parts) > 1 else lmin
        except (ValueError, IndexError):
            sys.exit("✗ Invalid range. Use format like: 1-10")
    audio_levels = set(range(lmin, lmax + 1))
    print(f"\n  Will embed audio for levels {lmin}–{lmax}.")

# ── Load and parse WK_DATA ──────────────────────────────────────────
print(f"\nReading {DATA_FILE}...")
with open(DATA_FILE, "r", encoding="utf-8") as f:
    data_js = f.read()

# Extract the JSON array from "const WK_DATA = [...];"
match = re.search(r'const WK_DATA\s*=\s*(\[.*\]);', data_js, re.DOTALL)
if not match:
    sys.exit("✗ Could not parse WK_DATA from wk_data.js")

items = json.loads(match.group(1))
print(f"  {len(items):,} items loaded.")

# ── Embed audio as base64 ───────────────────────────────────────────
embedded = 0
skipped  = 0
missing  = 0

if audio_levels:
    print(f"\nEmbedding audio for levels {lmin}–{lmax}...")
    vocab_in_range = [it for it in items if it["obj"] == "vocabulary" and it["level"] in audio_levels]
    total = len(vocab_in_range)

    for i, item in enumerate(vocab_in_range, 1):
        print(f"  [{i}/{total}] level {item['level']} · {item['char'][:6]:<6}", end="\r")
        new_audio = {}
        for key, local_path in item.get("audio", {}).items():
            fpath = local_path  # e.g. "audio/1234_f.mp3"
            if os.path.exists(fpath):
                with open(fpath, "rb") as af:
                    b64 = base64.b64encode(af.read()).decode("ascii")
                new_audio[key] = f"data:audio/mpeg;base64,{b64}"
                embedded += 1
            else:
                new_audio[key] = local_path  # keep original path as fallback
                missing += 1
        item["audio"] = new_audio

    # Items outside the audio range: clear local paths (they'll hit TTS fallback)
    for item in items:
        if item["obj"] == "vocabulary" and item["level"] not in audio_levels:
            # Remove local paths so the audio element fails fast → TTS
            item["audio"] = {}

    print(f"\n  ✓ {embedded:,} audio files embedded. {missing} missing files skipped.")

# ── Build modified JS ───────────────────────────────────────────────
new_data_js = (
    "// WaniKani mobile data — generated by make_mobile.py\n"
    f"// Audio embedded for levels {lmin}–{lmax}\n"
    f"const WK_DATA = {json.dumps(items, ensure_ascii=False, separators=(',', ':'))};\n"
)

# ── Patch HTML ──────────────────────────────────────────────────────
print(f"\nReading {HTML_FILE}...")
with open(HTML_FILE, "r", encoding="utf-8") as f:
    html = f.read()

if PLACEHOLDER not in html:
    sys.exit(f"\n✗ Could not find script placeholder in {HTML_FILE}.\nLooking for: {PLACEHOLDER}\n")

inline_tag = f"<script>\n{new_data_js}\n</script>"
combined   = html.replace(PLACEHOLDER, inline_tag)

# ── Write output ────────────────────────────────────────────────────
print(f"Writing {OUTPUT_FILE}...")
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(combined)

size_mb = os.path.getsize(OUTPUT_FILE) / 1_048_576
print(f"\n{'═'*42}")
print(f"✓ Done!  {OUTPUT_FILE}  ({size_mb:.1f} MB)")
print(f"  Copy this single file to your phone.")
print(f"  Open in Chrome — human voices for levels {lmin}–{lmax},")
print(f"  voice synthesis for any other levels.")
print(f"{'═'*42}\n")
